displayName=Clog Drop Rates
author=pairofcrocs
description=Shows drop rates and acquisition methods when hovering over items in the collection log
tags=collection,log,drop,rate,rarity,tooltip,acquire,shop
plugins=com.dropratesclog.DropRatesClogPlugin
build=standard
