package com.dropratesclog;

import com.google.gson.annotations.SerializedName;
import lombok.Data;

import java.util.Collections;
import java.util.List;

/**
 * One row from clog_items.json — the canonical "every collection-log item" table,
 * generated by scripts/scrape_clog_items.py by joining
 * Module:Collection_log/data.json with Bucket:Item_id.
 *
 * {@code wikiPage} (mapped from {@code wiki_page} in the JSON) is the deterministic
 * lookup key into drop_rates.json / buyable.json. For most items it equals the
 * in-game name; for variants (Medallion fragment, Decorative armour tiers, etc.)
 * it carries the disambiguating suffix the wiki uses.
 */
@Data
public class ClogItem
{
    private int          id;
    private String       name;
    private List<String> tabs = Collections.emptyList();

    @SerializedName("wiki_page")
    private String       wikiPage;
}
