"""
Builds drop_rates.json for the Drop Rates Collection Log RuneLite plugin.

Input:
  src/main/resources/com/dropratesclog/clog_items.json
    (generated by scripts/scrape_clog_items.py — gives us each clog item's
     in-game id, in-game name, and resolved wiki page).

Data source: the OSRS wiki's `dropsline` bucket (monster / skilling drops that
carry a numeric rarity). A rate is kept only if it is a fraction (e.g. "1/512",
"3 × 1/128", "90/18,014") or "always" — text rarities ("Very rare", "Unknown",
"Rare", "Once", "Varies") are dropped, as is any shop / reward-currency data,
which is covered by the curated Acquirable Items pipeline (buyable.json).

Output is keyed by each item's in-game item ID (as a string, e.g. "32388").
The plugin gets the ID directly from RuneLite on hover, so no string
matching is needed between in-game and wiki names.

Run (after scrape_clog_items.py has produced clog_items.json):
  pip install requests
  python scripts/scrape.py --out src/main/resources/com/dropratesclog/drop_rates.json
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import defaultdict
from pathlib import Path

import requests

BASE          = "https://oldschool.runescape.wiki"
API           = f"{BASE}/api.php"
HEADERS       = {"User-Agent": "DropRatesClog/1.0 (RuneLite plugin; contact via GitHub)"}
REQUEST_DELAY = 0.3


CLOG_ITEMS_DEFAULT = Path(__file__).resolve().parent / "clog_items.json"


def load_clog_items(path: Path) -> list[dict]:
    """Read the wiki-page-augmented clog list produced by scrape_clog_items.py."""
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found — run scripts/scrape_clog_items.py first."
        )
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def dropsline_query(item_name: str) -> list[dict]:
    """Query the wiki `dropsline` bucket for every drop row of one item."""
    escaped = item_name.replace('"', '\\"')
    lua = (
        f'bucket("dropsline").select("drop_json")'
        f'.where("item_name","{escaped}").limit(500).run()'
    )
    params = {"action": "bucket", "query": lua, "format": "json"}
    resp = requests.get(API, params=params, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    if "error" in data:
        return []

    result = []
    for row in data.get("bucket", []):
        dj = row.get("drop_json")
        if isinstance(dj, dict):
            result.append(dj)
        elif isinstance(dj, str):
            try:
                result.append(json.loads(dj))
            except json.JSONDecodeError:
                pass
    return result


# Items often appear in dropsline under a variant-suffixed name
# (e.g. "Ring of endurance (uncharged)" or "Prospector jacket#Motherlode Mine").
# The wikitext template that renders the drop table names the right key — scrape it.
_DROP_SOURCES_RX = re.compile(
    r"\{\{\s*Drop sources\s*\|\s*([^|}\n]+?)\s*(?:\||\}\})",
    re.IGNORECASE,
)


def find_drop_template_alts(item_name: str) -> list[str]:
    """Return any {{Drop sources|X}} keys mentioned in `item_name`'s wikitext."""
    params = {
        "action":    "parse",
        "page":      item_name,
        "prop":      "wikitext",
        "format":    "json",
        "redirects": 1,
    }
    try:
        resp = requests.get(API, params=params, headers=HEADERS, timeout=30)
        resp.raise_for_status()
    except Exception:
        return []
    wikitext = resp.json().get("parse", {}).get("wikitext", {}).get("*", "")
    return [m.group(1).strip() for m in _DROP_SOURCES_RX.finditer(wikitext)]


# --- rate parsing & validation -------------------------------------------------------

_MULTI_ROLL_RX = re.compile(r"^(\d+)\s*[×x]\s*(\d+(?:\.\d+)?)/(\d+(?:\.\d+)?)$")
_SIMPLE_RATE_RX = re.compile(r"^(\d+(?:\.\d+)?)/(\d+(?:\.\d+)?)$")


def rate_key(drop: dict) -> str:
    """Build the human-readable rate string from a dropsline row (e.g. "1/512" or
    "3 × 1/512"). Returns empty if the row has no rarity."""
    rarity = (drop.get("Rarity") or "").strip()
    if not rarity:
        return ""
    rolls = 1
    try:
        rolls = int(drop.get("Rolls", 1))
    except (TypeError, ValueError):
        pass
    if rolls > 1:
        return f"{rolls} × {rarity}"
    return rarity


def is_drop_rate(rate: str) -> bool:
    """A rate is kept only if it's a fraction or the word "always". Drops text rarities
    like "Very rare", "Unknown", "Rare", "Once", "Varies"."""
    if not rate:
        return False
    s = rate.replace(",", "").strip().lower()
    if s in ("always", "1/1"):
        return True
    if _MULTI_ROLL_RX.match(s):
        return True
    if _SIMPLE_RATE_RX.match(s):
        return True
    return False


def rate_to_float(rate: str) -> float | None:
    """Parse a kept rate to a probability for sorting; returns None if non-numeric."""
    s = rate.replace(",", "").strip().lower()
    if s in ("always", "1/1"):
        return 1.0
    m = _MULTI_ROLL_RX.match(s)
    if m:
        return int(m.group(1)) * float(m.group(2)) / float(m.group(3))
    m = _SIMPLE_RATE_RX.match(s)
    if m:
        return float(m.group(1)) / float(m.group(2))
    return None


def clean_source(dropped_from: str) -> str:
    if "#" in dropped_from:
        base, variant = dropped_from.split("#", 1)
        return f"{base} ({variant.replace('_', ' ')})"
    return dropped_from


def group_drops(drops: list[dict]) -> list[dict]:
    """Group dropsline rows by (rate, approx), keeping only fraction/always rates and
    sorting by best chance first."""
    groups: dict[tuple, list[str]] = defaultdict(list)

    for drop in drops:
        key    = rate_key(drop)
        if not is_drop_rate(key):
            continue
        approx = bool(drop.get("Approx", False))
        source = clean_source((drop.get("Dropped from") or "").strip())
        if source:
            groups[(key, approx)].append(source)

    def sort_key(item):
        (rate, approx), _ = item
        val = rate_to_float(rate)
        return (val is None, -(val or 0))

    result = []
    for (rate, approx), sources in sorted(groups.items(), key=sort_key):
        result.append({"kind": "drop", "rate": rate, "approx": approx, "sources": sources})
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, help="Output JSON path")
    parser.add_argument("--clog-items", default=str(CLOG_ITEMS_DEFAULT),
                        help="Path to clog_items.json (default: resources/com/dropratesclog/clog_items.json)")
    parser.add_argument("--overrides", default=str(Path(__file__).resolve().parent / "drop_rate_overrides.json"),
                        help="Curated id-keyed overrides merged over the scraped output. For drops the "
                             "dropsline bucket can't express (per-delve-level rates, etc.). Pass '' to skip.")
    parser.add_argument("--merge-prev", default="",
                        help="Previously-published drop_rates.json. Any item that HAD data there but the "
                             "wiki returned nothing for this run (a transient failure) is carried over, so "
                             "items never silently vanish. Genuine rate changes still win (fresh scrape > prev).")
    args = parser.parse_args()

    items = load_clog_items(Path(args.clog_items))
    print(f"Loaded {len(items)} clog items from {args.clog_items}")

    drop_rates: dict[str, list] = {}
    no_data: list[dict] = []
    total_rows = total_kept = 0

    for i, item in enumerate(items, 1):
        wiki_page = item["wiki_page"]
        name      = item["name"]
        print(f"[{i:>4}/{len(items)}] {wiki_page}")
        entries: list[dict] = []

        # Lookup chain mirrors the wiki-side Source module:
        #   1. wiki_page (page_name_sub) — most specific
        #   2. bare page (strip #anchor)
        #   3. bare clog name             — last resort
        tried: list[str] = []
        for key in (wiki_page, wiki_page.split("#", 1)[0], name):
            if key in tried:
                continue
            tried.append(key)
            try:
                drops = dropsline_query(key)
            except Exception as exc:
                print(f"          !! dropsline '{key}': {exc}")
                drops = []
            total_rows += len(drops)
            kept = group_drops(drops)
            if kept:
                entries = kept
                break
            time.sleep(REQUEST_DELAY)

        # Final fallback: {{Drop sources|X}} keys mentioned in the article wikitext.
        if not entries:
            for probe in (wiki_page.split("#", 1)[0], name):
                alts = find_drop_template_alts(probe)
                for alt in alts:
                    if alt in tried:
                        continue
                    tried.append(alt)
                    try:
                        kept = group_drops(dropsline_query(alt))
                    except Exception as exc:
                        print(f"          !! dropsline alt '{alt}': {exc}")
                        kept = []
                    if kept:
                        entries.extend(kept)
                    time.sleep(REQUEST_DELAY)
                if entries:
                    print(f"          ↳ recovered via templates: {alts}")
                    break

        if entries:
            drop_rates[str(item["id"])] = entries
            total_kept += sum(len(g["sources"]) for g in entries)
        else:
            no_data.append(item)

        time.sleep(REQUEST_DELAY)

    # Stickiness: carry over any item that previously had data but the wiki gave us nothing this
    # run. Transient dropsline failures must never *delete* an item's data — stale beats empty for
    # a drop-rate tooltip. Fresh results still win; only genuine gaps are back-filled.
    if args.merge_prev:
        try:
            with open(args.merge_prev, encoding="utf-8") as f:
                prev = json.load(f)
            carried = [k for k in prev if k not in drop_rates]
            for k in carried:
                drop_rates[k] = prev[k]
            if carried:
                print(f"Carried over {len(carried)} item(s) missing from this scrape (transient?): "
                      f"{', '.join(carried[:10])}{' …' if len(carried) > 10 else ''}")
        except FileNotFoundError:
            print(f"No --merge-prev file at {args.merge_prev} — skipping carry-over")

    # Curated overrides win over the scraped single-rate. These are drops the dropsline bucket
    # can't express — e.g. Doom of Mokhaiotl uniques, whose rate improves per delve level (the
    # full curve lives only in a hand-authored wikitable). See drop_rate_overrides.json.
    if args.overrides:
        try:
            with open(args.overrides, encoding="utf-8") as f:
                overrides = json.load(f)
            drop_rates.update(overrides)
            print(f"Applied {len(overrides)} curated override(s) from {args.overrides}")
        except FileNotFoundError:
            print(f"No overrides file at {args.overrides} — skipping")

    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(drop_rates, f, indent=2, ensure_ascii=False, sort_keys=True)

    print(f"\nWrote {len(drop_rates)} items to {args.out}")
    print(f"Kept {total_kept} source rows across all items "
          f"(scraped {total_rows} raw rows from dropsline)")
    if no_data:
        print(f"No drop-rate data for {len(no_data)} items "
              f"(shop / currency / text-rarity-only items live in buyable.json)")


if __name__ == "__main__":
    main()
